apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../environments/overlays/rfe

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: rfe-nexus
    path: nexus-app-patch.yaml
