kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "ansible-rfe-build" 
spec:
  runPolicy: "Serial" 
  source:
    type: Dockerfile
    dockerfile: "FROM registry.access.redhat.com/ubi8/python-38\nUSER 0\nRUN dnf update -y\nRUN pip install --upgrade pip\nRUN pip install openshift\nRUN pip install ansible==2.9.*\nUSER 1001"
  strategy:
    type: Docker
    dockerstrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/python-38
  output: 
    to:
      kind: "ImageStreamTag"
      name: "ansible-rfe-build:latest"
