apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github
  namespace: group-sync-operator
spec:
  encryptedData:
    token: AgAIhNgiHVknPKleqWjj9BGAWNZqfH8BnxmR+W0HM9eKMCyL9ZtnRqeq8STF1iBT0U46p8itSi2Hm+BBmP+GhdpCA9IdKOqSoegAHOacd1W3IdU2b/BMNGn+jvXYrM3RivT3Q+vrCaxn2bW3HLz0i5fO49K2pnTdjzVZtvqaJQQ39nX2YMPozHQBcjDzpIXLfpRdFYw25E6p5ig//mW1BbhXmT5Ng1dXhM+CCwCfeslotbLXCBN9IXBIlNZcaMGzA+iTm9I8FYYnNdo1OEOhGV6YRJM2a2ukzW6Dfb7z9Zz4z5hzM+ResJcbFGQd8YK2C8qJgoaOD8UPeB0HkaBog7qWLim9vFp32Iz2uZbSvf/IwFCxMzRnH4B8D+cd9fjLEjYYNQUeuwee5ecZnsq0AHGVCeVvt0WBBf+DIn1XAGNaRhj6/dz+GTtYN4tz6r+4Q/nUGgfhtc0EeSVi1AfNMitkQdEMov1m7AL0ZEVs1c0acxR2KImilmpM+6fEwwjN5HVBpqxiih03ph75YyeGBvZgoa03jCDaxLAC6WdqUCT0SB+CrzRoY5ypv/2aIzab+T+sw2+hyRmHVk7mpMOhkIUurJLC4/jtu/MApiYy1fzQgYz6y8XVLhK7d9nIy4/YhJ4DCpBhQnbK68iLtVE6cyJ80ARtoA+29dO9YMGhVVM6Fye7zpKb8WUZLDDRcPNR54K667m/FLhdPKkt4HJdUNR3rE3eVbRDCq59I8hB3PvW/Tgej8aSbLzF
  template:
    metadata:
      name: github
      namespace: group-sync-operator
