apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../manifests/configs/auth/base

patchesStrategicMerge:
  - oauth.yaml

resources:
  - group-sync-github-secret.yaml
  - oauth-github-secret.yaml
  - group-sync-operator-namespace.yaml
  - group-sync-operator-operatorgroup.yaml
  - group-sync-operator-subscription.yaml
  - groupsync.yaml
