apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgArSi3erN8ZBFuK4sa/87+xKF005vxWRgIWgQnzIsXca2SNxzI4owuT/av7AdX0BBoMV7Mfmq/Gmti4OFTJUCsepTTf89QEu5g2pB8u2bcIovqRN8ZOltRgphNDrTSa2aEyRRJiC/oCnBKblCPw6yT8u27IzVq30n6/8zyYvVdlVKifXY0gKP59LfhdYh94OJA0uZ+AMsuZyAsYTYHZisgUxWU7VhnaT1TJc+jWgOL0cqdkubIbYlUkZxWxOVewk+1Dq1x50QJWqVKrj7vQxt+q/4wqGGzaJ4CiDz2/8Z/vQF/NQbHRcFHhPq/l8r/2fKvnoawLYtGsGmqgMej8yw1s0Ll6ImGiE7pjiv8vbUGALWsVGi9xBned4z0uEBirL9cZYWVw0Ooqz6RG9ZpddOOHq4xXhV22H3XZo/XQ7+oS8CgZtWxCfQW2P+uNhijgbOIQi/KedY8Wx40DeH+KaG4fD+0fD1koBaEeohbou+SyDmK6DfGJZ3HUlWBFPaAUuw8Lf7QuCsJj+pMKG9DbrBQfx4twGoLe20pXqJlcgx5XFpKoAQ7KgfI34clQzZyrYrjDYG8TF8Blxf9RITo3JJHRafcliuBJWoYtZuhV10hSAN/tKPLab64PEtQBEKIEyUtql4/dYq4ks4CpYSgRb/kI0abawUJSuQevotmF0sBqoIzfbaXFGOI0fBwUZlgJgaCwpF6HAmHlfHud9wG/cZnADnR+Y94xK/Bgr+GBAvE5x3JfjZBPMBi2
  template:
    metadata:
      name: github
      namespace: openshift-config
