apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
  name: upload-kickstart
spec:
  workspaces:
    - name: workspace
  params:
    - name: rfe-tarball-url
      description: URL of the RFE Tarball
    - name: kickstart-path
      description: Directory containing kickstart file
      type: string
    - name: kickstart-destination-dir
      description: Directory Kickstart file should be created
      type: string
    - name: extra-ansible-variables
      description: Extra Ansible variables
      default: ""
      type: string
  results:
    - name: artifact-repository-storage-url
      description: Location where the asset is stored in the artifact repository
    - name: serving-storage-url
      description: Location where the asset is served
  steps:
    - name: build-rfe-tarball
      image: image-registry.openshift-image-registry.svc:5000/rfe/ansible-rfe-runner:latest
      workingDir: /workspace/workspace
      args:
        - |-
          cd tooling/ansible
          ansible-galaxy collection install -r collections/requirements.yaml
          ansible-playbook playbooks/upload-kickstart.yaml -e rfe_tarball_url=$(params.rfe-tarball-url) -e kickstart_file=$(params.kickstart-path) -e kickstart_destination_dir=$(params.kickstart-destination-dir) -e artifact_repository_url_output_file=$(results.artifact-repository-storage-url.path) -e storage_url_output_file=$(results.serving-storage-url.path) $(params.extra-ansible-variables)
      command:
        - /bin/bash
        - -c
