apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../manifests/rfe/httpd/base
  - ../../../manifests/rfe/nexus/base
  - ../../../manifests/rfe/image-builder-vm/base
  - ../../../manifests/rfe/rbac/base
  - ../../../manifests/rfe/ansible-rfe-runner/base

resources:
  - rfe-namespace.yaml
