apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../manifests/argocd/apps/rfe/ansible-rfe-runner/base
  - ../../../manifests/argocd/apps/rfe/httpd/base
  - ../../../manifests/argocd/apps/rfe/image-builder-vm/base
  - ../../../manifests/argocd/apps/rfe/nexus/base
  - ../../../manifests/argocd/apps/rfe/pipelines/base
  - ../../../manifests/argocd/apps/rfe/rbac/base

resources:
  - rfe-namespace.yaml
