apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../environments/overlays/bootstrap

resources:
  - cluster-config-manager-app.yaml
  - rfe-app.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
    path: patch-argocd-resource.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    path: patch-argocd-application.yaml
