kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ansible-rfe-runner
  namespace: rfe
spec:
  runPolicy: Serial
  source:
    type: Dockerfile
    dockerfile: |
<<<<<<< HEAD
    
      #pull ubi python image
      FROM registry.access.redhat.com/ubi8/python-38
      
      #set user to root
      USER 0
      
      #run base image update, pip upgrade, pip openshift libraries, install ansible 2.9.x
      RUN dnf update -y && \
          pip install --upgrade pip && \
          pip install openshift && \
          pip install ansible==2.9.*
      
      #set user to default
      USER 1001
          
  strategy:
    type: Docker
    dockerstrategy:
=======
      FROM registry.access.redhat.com/ubi8/python-38
      USER 0
      RUN dnf update -y && \
          pip install --upgrade pip && \
          pip install openshift && \
          pip install jmespath && \
          pip install netaddr && \
          pip install ansible==2.9.* && \
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | \
            tar -xvzf - -C /usr/local/bin/ oc && chmod 755 /usr/local/bin/oc && ln -s /usr/local/bin/oc /usr/local/bin/kubectl

      USER 1001

  strategy:
    type: Docker
    dockerStrategy:
>>>>>>> 03f75fa79abf2ab316a009792a956bc1c78e2140
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/python-38
  triggers:
    - type: ConfigChange
<<<<<<< HEAD
  output: 
=======
  output:
>>>>>>> 03f75fa79abf2ab316a009792a956bc1c78e2140
    to:
      kind: ImageStreamTag
      name: ansible-rfe-runner:latest
